Repository Zip-Bab/zip_bab, pull requests merged in 2023-10, with the labels that each got.

#11 레시피 JSON 파싱
  pom.xml
  src/main/java/parse/json/RecipeJsonParse.java
  src/main/resources/writeFile.txt
Labels: documentation

#13 파싱 데이터 추가
  src/main/java/parse/json/RecipeJsonParse.java
  src/main/resources/writeFile.txt
Labels: documentation

#19 recipe와 review 합치기
  src/main/java/recipe/handler/DetailHandler.java
  src/main/java/review/Review.java
  src/main/java/review/ReviewDao.java
  src/main/java/review/ReviewMember.java
  src/main/java/review/ReviewService.java
  src/main/java/review/handler/ReviewCreateHandler.java
  src/main/java/review/handler/ReviewDelHandler.java
  src/main/java/review/handler/ReviewEditHandler.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/recipe/detail.jsp
  src/main/webapp/review/create.jsp
  src/main/webapp/review/edit.jsp
Labels: enhancement

#22 MemberRecipe 구조 구성
  src/main/java/mebmerofrecipe/MemberRecipe.java
  src/main/java/mebmerofrecipe/MemberRecipeDao.java
  src/main/java/mebmerofrecipe/MemberRecipeService.java
  src/main/java/mebmerofrecipe/handler/AddHandler.java
  src/main/java/mebmerofrecipe/handler/DelHandler.java
  src/main/java/mebmerofrecipe/handler/DetailHandler.java
  src/main/java/mebmerofrecipe/handler/EditHandler.java
  src/main/java/mebmerofrecipe/handler/ImgDelHandler.java
  src/main/java/mebmerofrecipe/handler/ListHandler.java
  src/main/java/parse/json/RecipeJsonParse.java
Labels: enhancement

#23 회원가입, 로그인, 회원 정보 수정, 로그아웃
  src/main/java/member/Member.java
  src/main/java/member/MemberDao.java
  src/main/java/member/MemberService.java
  src/main/java/member/handler/EditHandler.java
  src/main/java/member/handler/IdCheckHandler.java
  src/main/java/member/handler/JoinHandler.java
  src/main/java/member/handler/LoginHandler.java
  src/main/java/member/handler/OutHandler.java
  src/main/java/review/ReviewService.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/index.jsp
  src/main/webapp/member/edit.jsp
  src/main/webapp/member/join.jsp
  src/main/webapp/member/js/join.js
  src/main/webapp/member/login.jsp
  src/main/webapp/nav.jsp
Labels: enhancement

#24 Recipe detail 및 list 작업
  src/main/java/recipe/Page.java
  src/main/java/recipe/Recipe.java
  src/main/java/recipe/handler/DetailHandler.java
  src/main/webapp/recipe/detail.jsp
  src/main/webapp/recipe/list.jsp
Labels: enhancement

#25 addHandler 작성
  pom.xml
  src/main/java/handler/Handler.java
  src/main/java/mebmerofrecipe/handler/DelHandler.java
  src/main/java/memberrecipe/MemberRecipe.java
  src/main/java/memberrecipe/MemberRecipeDao.java
  src/main/java/memberrecipe/MemberRecipeService.java
  src/main/java/memberrecipe/handler/AddHandler.java
  src/main/java/memberrecipe/handler/DelHandler.java
  src/main/java/memberrecipe/handler/DetailHandler.java
  src/main/java/memberrecipe/handler/EditHandler.java
  src/main/java/memberrecipe/handler/ImgDelHandler.java
  src/main/java/memberrecipe/handler/ListHandler.java
  src/main/java/sqlsession/Factory.java
  src/main/resources/.env.template
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/member/edit.jsp
  src/main/webapp/memberrecipe/create.jsp
Labels: enhancement

#26 [Add] 후기 선호도, 후기 로그인 권한 기능 추가
  src/main/java/member/handler/LoginHandler.java
  src/main/java/recipe/RecipeDao.java
  src/main/java/recipe/RecipePref.java
  src/main/java/recipe/RecipeService.java
  src/main/java/recipe/handler/DetailHandler.java
  src/main/java/req/DispatcherServlet.java
  src/main/java/review/ReviewMember.java
  src/main/java/review/handler/ReviewCreateHandler.java
  src/main/java/review/handler/ReviewDelHandler.java
  src/main/java/review/handler/ReviewEditHandler.java
  src/main/webapp/recipe/detail.jsp
  src/main/webapp/review/create.jsp
  src/main/webapp/review/edit.jsp
Labels: enhancement

#27 프로필 사진 생성
  src/main/java/member/Member.java
  src/main/java/member/MemberDao.java
  src/main/java/member/MemberService.java
  src/main/java/member/handler/EditHandler.java
  src/main/java/member/handler/JoinHandler.java
  src/main/java/member/handler/LoginHandler.java
  src/main/java/sqlsession/Factory.java
  src/main/webapp/images/profile/고양이.jpg
  src/main/webapp/images/profile/고양이1.jpg
  src/main/webapp/images/profile/고양이10.jpg
  src/main/webapp/images/profile/고양이11.jpg
  src/main/webapp/images/profile/고양이12.jpg
  src/main/webapp/images/profile/고양이2.jpg
  src/main/webapp/images/profile/고양이3.jpg
  src/main/webapp/images/profile/고양이4.jpg
  src/main/webapp/images/profile/고양이5.jpg
  src/main/webapp/images/profile/고양이6.jpg
  src/main/webapp/images/profile/고양이7.jpg
  src/main/webapp/images/profile/고양이8.jpg
  src/main/webapp/images/profile/고양이9.jpg
  src/main/webapp/index.jsp
  src/main/webapp/member/edit.jsp
  src/main/webapp/member/login.jsp
  src/main/webapp/nav.jsp
Labels: enhancement

#28 [Fix] bug
  pom.xml
  src/main/java/handler/MainHandler.java
  src/main/java/member/handler/LoginHandler.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/nav.jsp
  src/main/webapp/recipe/list.jsp
Labels: bug

#31 최근 본 레시피 기능 추가
  src/main/webapp/index.jsp
  src/main/webapp/member/login.jsp
  src/main/webapp/recipe/detail.jsp
  src/main/webapp/recipe/js/detail_view_history.js
Labels: enhancement

#32 프로필 이미지 원형으로 변경, 팔로우 기능 추가, 코드 최적화
  src/main/java/follow/FollowDao.java
  src/main/java/follow/FollowService.java
  src/main/java/follow/handler/AddHandler.java
  src/main/java/follow/handler/MypageHandler.java
  src/main/java/member/handler/EditHandler.java
  src/main/java/member/handler/JoinHandler.java
  src/main/webapp/images/profile/고양이.jpg
  src/main/webapp/images/profile/고양이1.jpg
  src/main/webapp/images/profile/고양이10.jpg
  src/main/webapp/images/profile/고양이11.jpg
  src/main/webapp/images/profile/고양이12.jpg
  src/main/webapp/images/profile/고양이2.jpg
  src/main/webapp/images/profile/고양이3.jpg
  src/main/webapp/images/profile/고양이4.jpg
  src/main/webapp/images/profile/고양이5.jpg
  src/main/webapp/images/profile/고양이6.jpg
  src/main/webapp/images/profile/고양이7.jpg
  src/main/webapp/images/profile/고양이8.jpg
  src/main/webapp/images/profile/고양이9.jpg
  src/main/webapp/member/edit.jsp
Labels: enhancement

#33 Recipe 페이징 초안 및 detail 작업
  src/main/java/recipe/Page.java
  src/main/java/recipe/Recipe.java
  src/main/java/recipe/RecipeDao.java
  src/main/java/recipe/RecipeService.java
  src/main/java/recipe/handler/ListByPageHandler.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/nav.jsp
  src/main/webapp/recipe/detail.jsp
  src/main/webapp/recipe/list.jsp
Labels: enhancement

#35 팔로우, 팔로우 취소 기능 추가
  src/main/java/follow/FollowDao.java
  src/main/java/follow/FollowService.java
  src/main/java/follow/handler/AddHandler.java
  src/main/java/follow/handler/MypageHandler.java
  src/main/java/member/MemberDao.java
  src/main/java/member/MemberService.java
  src/main/java/member/handler/EditHandler.java
  src/main/java/sqlsession/Factory.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/follow/mypage.jsp
  src/main/webapp/nav.jsp
Labels: enhancement

#36 리뷰 like 기능
  src/main/java/recipe/handler/DetailHandler.java
  src/main/java/review/ReviewDao.java
  src/main/java/review/ReviewMember.java
  src/main/java/review/ReviewService.java
  src/main/java/review/handler/ReviewLikeHandler.java
  src/main/java/review/handler/ReviewListHandler.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/footer.jsp
  src/main/webapp/images/profile/32.jpg
  src/main/webapp/index.jsp
  src/main/webapp/recipe/css/detail.css
  src/main/webapp/recipe/detail.jsp
  src/main/webapp/recipe/js/detail_view_history.js
  src/main/webapp/recipe/js/review.js
  src/main/webapp/recipe/js/review_like.js
Labels: documentation, front

#34 북마크 구현 및 레시피 페이징 작업
  src/main/java/bookmark/Bookmark.java
  src/main/java/bookmark/BookmarkDao.java
  src/main/java/bookmark/BookmarkService.java
  src/main/java/bookmark/handler/BookmarkHandler.java
  src/main/java/recipe/Recipe.java
  src/main/java/recipe/RecipeDao.java
  src/main/java/recipe/RecipeService.java
  src/main/java/recipe/handler/DetailHandler.java
  src/main/java/recipe/handler/GetByIngredientHandler.java
  src/main/java/recipe/handler/GetByTitleHandler.java
  src/main/java/recipe/handler/ListByPageHandler.java
  src/main/java/recipe/handler/ListHandler.java
  src/main/java/sqlsession/Factory.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/css/index.css
  src/main/webapp/footer.jsp
  src/main/webapp/images/main/main.jpg
  src/main/webapp/images/recipe/default.jpg
  src/main/webapp/index.jsp
  src/main/webapp/nav.jsp
  src/main/webapp/recipe/css/list.css
  src/main/webapp/recipe/css/remote.css
  src/main/webapp/recipe/detail.jsp
  src/main/webapp/recipe/list.jsp
Labels: enhancement

#39 이미지 수정 기능 추가
  src/main/java/handler/Handler.java
  src/main/java/memberrecipe/MemberRecipeDao.java
  src/main/java/memberrecipe/MemberRecipeService.java
  src/main/java/memberrecipe/handler/AddHandler.java
  src/main/java/memberrecipe/handler/DelHandler.java
  src/main/java/memberrecipe/handler/DetailHandler.java
  src/main/java/memberrecipe/handler/EditHandler.java
  src/main/java/memberrecipe/handler/ImgDelHandler.java
  src/main/java/memberrecipe/handler/ImgEditHandler.java
  src/main/java/memberrecipe/handler/ListHandler.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/memberrecipe/css/list.css
  src/main/webapp/memberrecipe/css/remote.css
  src/main/webapp/memberrecipe/detail.jsp
  src/main/webapp/memberrecipe/edit.jsp
  src/main/webapp/memberrecipe/js/detail_view_history.js
  src/main/webapp/memberrecipe/list.jsp
  src/main/webapp/nav.jsp
Labels: enhancement

#40 Recipe 상세페이지 View 수정
  src/main/webapp/recipe/css/detail.css
  src/main/webapp/recipe/detail.jsp
Labels: enhancement

#41 마이페이지 뷰 변경
  src/main/java/follow/handler/MypageHandler.java
  src/main/java/member/handler/EditHandler.java
  src/main/webapp/follow/mypage.jsp
  src/main/webapp/member/edit.jsp
  src/main/webapp/member/mypage.jsp
  src/main/webapp/member/projection/assets/css/font-awesome.min.css
  src/main/webapp/member/projection/assets/css/main.css
  src/main/webapp/member/projection/assets/fonts/fontawesome-webfont.eot
  src/main/webapp/member/projection/assets/fonts/fontawesome-webfont.svg
  src/main/webapp/member/projection/assets/fonts/fontawesome-webfont.ttf
  src/main/webapp/member/projection/assets/fonts/fontawesome-webfont.woff
  src/main/webapp/member/projection/assets/fonts/fontawesome-webfont.woff2
  src/main/webapp/member/projection/assets/js/jquery.min.js
  src/main/webapp/member/projection/assets/js/main.js
  src/main/webapp/member/projection/assets/js/skel.min.js
  src/main/webapp/member/projection/assets/js/util.js
  src/main/webapp/member/projection/edit.jsp
  src/main/webapp/member/projection/elements.html
  src/main/webapp/member/projection/generic.html
  src/main/webapp/member/projection/images/pic01.jpg
  src/main/webapp/member/projection/images/pic02.jpg
  src/main/webapp/member/projection/index.jsp
  src/main/webapp/nav.jsp
Labels: enhancement

#42 [Modify] font, recipe float-menu
  src/main/java/review/handler/ReviewEditHandler.java
  src/main/webapp/css/base.css
  src/main/webapp/css/index.css
  src/main/webapp/images/profile/32.jpg
  src/main/webapp/index.jsp
  src/main/webapp/recipe/css/detail.css
  src/main/webapp/recipe/css/remote.css
  src/main/webapp/recipe/detail.jsp
  src/main/webapp/recipe/js/detail_view_history.js
  src/main/webapp/recipe/js/review.js
Labels: front

#43 memberrecipe 버그 수정, index, navbar 변경
  src/main/java/member/handler/EditHandler.java
  src/main/java/memberrecipe/handler/AddHandler.java
  src/main/webapp/index.jsp
  src/main/webapp/memberrecipe/create.jsp
  src/main/webapp/memberrecipe/detail.jsp
  src/main/webapp/memberrecipe/edit.jsp
  src/main/webapp/memberrecipe/list.jsp
  src/main/webapp/nav.jsp
Labels: bug, front

#46 북마크 기능 추가
  src/main/java/bookmark/handler/BookmarkHandler.java
  src/main/java/follow/handler/MypageHandler.java
  src/main/java/recipe/handler/ListByPageHandler.java
  src/main/webapp/member/css/mypage.css
  src/main/webapp/member/mypage.jsp
  src/main/webapp/recipe/list.jsp
Labels: enhancement

#47 레시피 북마크 수정
  src/main/java/bookmark/handler/BookmarkHandler.java
  src/main/java/recipe/handler/ListByPageHandler.java
Labels: enhancement

#48 디테일 테마 추가, 이미지 삭제 추가
  src/main/java/memberrecipe/handler/ImgDelHandler.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/memberrecipe/css/detail.css
  src/main/webapp/memberrecipe/css/list.css
  src/main/webapp/memberrecipe/css/remote.css
  src/main/webapp/memberrecipe/detail.jsp
  src/main/webapp/memberrecipe/detail2.jsp
  src/main/webapp/memberrecipe/edit.jsp
  src/main/webapp/memberrecipe/js/detail_view_history.js
  src/main/webapp/memberrecipe/js/review.js
  src/main/webapp/memberrecipe/js/review_like.js
Labels: enhancement

#49 네이버 쇼핑
  src/main/java/recipe/handler/NaverShoppingHandler.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/recipe/css/detail.css
  src/main/webapp/recipe/detail.jsp
Labels: enhancement

#50 선호도 정렬 추가
  src/main/java/bookmark/handler/BookmarkHandler.java
  src/main/java/memberrecipe/MemberRecipeDao.java
  src/main/java/memberrecipe/MemberRecipeService.java
  src/main/java/memberrecipe/dto/MemberRecipePrefDto.java
  src/main/java/memberrecipe/handler/ListHandler.java
  src/main/java/recipe/RecipeDao.java
  src/main/java/recipe/RecipeService.java
  src/main/java/recipe/dto/RecipePrefDto.java
  src/main/java/recipe/handler/GetByTitleHandler.java
  src/main/java/recipe/handler/ListByPageHandler.java
  src/main/webapp/images/logo/z_no_image.png
  src/main/webapp/member/mypage.jsp
  src/main/webapp/memberrecipe/list.jsp
  src/main/webapp/nav.jsp
  src/main/webapp/recipe/list.jsp
Labels: enhancement

#51 네이버 쇼핑 api 파싱
  src/main/java/parse/json/RecipeJsonParse.java
  src/main/java/recipe/handler/NaverShoppingHandler.java
  src/main/java/shopping/NaverShoppingInfo.java
  src/main/java/shopping/handler/ApiNaverShoppingSearch.java
Labels: enhancement

#52 [Add] memberrecipe bookmark
  src/main/java/memberrecipe/MemberRecipeDao.java
  src/main/java/memberrecipe/MemberRecipeService.java
  src/main/java/memberrecipe/handler/BookmarkHandler.java
  src/main/java/review/ReviewDao.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/memberrecipe/list.jsp
Labels: enhancement

#53 팔로우 목록보기 추가
  src/main/java/follow/FollowDao.java
  src/main/java/follow/FollowService.java
  src/main/java/follow/handler/AddHandler.java
  src/main/java/follow/handler/Follow.java
  src/main/java/follow/handler/FollowerListHandler.java
  src/main/java/follow/handler/FollowingListHandler.java
  src/main/java/follow/handler/MypageHandler.java
  src/main/java/member/MemberDao.java
  src/main/java/member/MemberService.java
  src/main/java/member/handler/EditHandler.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/member/followList.jsp
  src/main/webapp/member/mypage.jsp
  src/main/webapp/member/projection/assets/css/main.css
  src/main/webapp/member/projection/edit.jsp
  src/main/webapp/member/projection/index.jsp
Labels: enhancement

#54 재료 표시 변경
  src/main/java/memberrecipe/handler/DetailHandler.java
  src/main/webapp/memberrecipe/detail.jsp
  src/main/webapp/memberrecipe/detail2.jsp
Labels: enhancement

#55 NaverShopping 데이터 연동
  src/main/java/shopping/handler/ApiNaverShoppingSearchHandler.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/recipe/css/detail.css
  src/main/webapp/recipe/css/naverShopping.css
  src/main/webapp/recipe/detail.jsp
  src/main/webapp/recipe/naverShopping.jsp
Labels: enhancement

#56 member recipe 에 review 추가
  src/main/java/memberrecipe/MemberRecipeDao.java
  src/main/java/memberrecipe/MemberRecipeService.java
  src/main/java/memberrecipe/handler/DetailHandler.java
  src/main/java/recipereview/RecipeReview.java
  src/main/java/recipereview/RecipeReviewDao.java
  src/main/java/recipereview/RecipeReviewService.java
  src/main/java/recipereview/dto/RecipeReviewMember.java
  src/main/java/recipereview/handler/CreateHandler.java
  src/main/java/recipereview/handler/DelHandler.java
  src/main/java/recipereview/handler/EditHandler.java
  src/main/java/recipereview/handler/LikeHandler.java
  src/main/java/review/handler/ReviewListHandler.java
  src/main/java/sqlsession/Factory.java
  src/main/webapp/WEB-INF/commands.properties
  src/main/webapp/images/memberrecipe/16.jpg
  src/main/webapp/memberrecipe/detail.jsp
  src/main/webapp/memberrecipe/js/review.js
  src/main/webapp/memberrecipe/js/review_like.js
  src/main/webapp/recipe/detail.jsp
Labels: enhancement

#57 회원가입 뷰 작업
  src/main/java/member/handler/EditHandler.java
  src/main/java/member/handler/JoinHandler.java
  src/main/webapp/member/join.jsp
  src/main/webapp/member/projection/assets/css/main.css
  src/main/webapp/member/projection/edit.jsp
  src/main/webapp/member/projection/index.jsp
  src/main/webapp/member/projection/join.jsp
Labels: enhancement

#58 팔로우 리스트 뷰 생성
  src/main/java/follow/handler/FollowerListHandler.java
  src/main/java/follow/handler/FollowingListHandler.java
  src/main/webapp/index.jsp
  src/main/webapp/member/followList.jsp
  src/main/webapp/member/projection/index.jsp
  src/main/webapp/member/projection/join.jsp
Labels: enhancement

#59 검색 기능, 버그 수정
  src/main/java/memberrecipe/MemberRecipeDao.java
  src/main/java/memberrecipe/handler/ListHandler.java
  src/main/java/recipe/RecipeDao.java
  src/main/java/recipe/handler/ListByPageHandler.java
  src/main/webapp/images/memberrecipe/161.jpg
  src/main/webapp/memberrecipe/js/detail_view_history.js
  src/main/webapp/memberrecipe/js/list.js
  src/main/webapp/memberrecipe/list.jsp
  src/main/webapp/recipe/js/detail_view_history.js
  src/main/webapp/recipe/js/list.js
  src/main/webapp/recipe/list.jsp
Labels: enhancement

#61 기타 버그 수정 및 북마크 view 수정
  src/main/webapp/member/css/mypage.css
  src/main/webapp/member/join.jsp
  src/main/webapp/member/mypage.jsp
  src/main/webapp/nav.jsp
  src/main/webapp/recipe/detail.jsp
Labels: enhancement

#66 팔로우 버튼 수정
  src/main/java/follow/handler/MypageHandler.java
  src/main/java/member/handler/MypageHandler.java
  src/main/webapp/member/mypage.jsp
Labels: enhancement

#67 멤버 레시피
  src/main/webapp/memberrecipe/css/detail.css
  src/main/webapp/memberrecipe/detail.jsp
Labels: enhancement

#68 유저레시피 테마 추가
  src/main/webapp/memberrecipe/css/styles.css
  src/main/webapp/memberrecipe/index.html
  src/main/webapp/memberrecipe/js/scripts.js
Labels: enhancement

#70 멤버레시피 edit 수정
  src/main/java/memberrecipe/MemberRecipeDao.java
  src/main/java/memberrecipe/handler/EditHandler.java
  src/main/webapp/memberrecipe/edit.jsp
Labels: enhancement

#73 유저 레시피 변경
  src/main/java/memberrecipe/handler/AddHandler.java
  src/main/java/memberrecipe/handler/EditHandler.java
  src/main/webapp/memberrecipe/create2.jsp
  src/main/webapp/memberrecipe/edit.jsp
  src/main/webapp/memberrecipe/edit2.jsp
  src/main/webapp/memberrecipe/list.jsp
Labels: enhancement

#74 유저 레시피 수정 오류 수정
  src/main/webapp/memberrecipe/edit2.jsp
Labels: enhancement

#75 유저 레시피 이미지 변경 팝업 수정
  src/main/webapp/memberrecipe/edit2.jsp
Labels: enhancement

#76 [Add] 마이페이지에 작성한 게시글 추가
  src/main/java/member/handler/MypageHandler.java
  src/main/java/memberrecipe/MemberRecipeDao.java
  src/main/java/memberrecipe/MemberRecipeService.java
  src/main/webapp/member/css/mypage.css
  src/main/webapp/member/mypage.jsp
  src/main/webapp/memberrecipe/detail.jsp
Labels: enhancement

#79 [Fix] recipe history 중복 버그
  src/main/webapp/memberrecipe/js/detail_view_history.js
  src/main/webapp/recipe/js/detail_view_history.js
Labels: bug

#80 최근 본 레시피 버그수정
  src/main/webapp/recipe/js/detail_view_history.js
Labels: bug
